# Generated by Django 5.0.6 on 2024-07-19 05:20

import concurrency.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, choices=[('1', '風景'), ('2', '植物'), ('3', '動物・ペット')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField()),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
