# Generated by Django 5.0.6 on 2024-07-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_name',
        ),
    ]
