# Generated by Django 5.0.6 on 2024-07-26 08:41

import concurrency.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_remove_image_file_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='画像'),
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40)),
                ('caption', models.CharField(blank=True, max_length=1000)),
                ('classification', models.CharField(blank=True, choices=[('1', 'ノーマル'), ('2', 'ポエム風')], max_length=1)),
                ('font', models.CharField(blank=True, choices=[('1', 'ゴシック'), ('2', '明朝'), ('3', '丸ゴシック')], max_length=1)),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField()),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_poem_id', models.ManyToManyField(to='poem.poem')),
            ],
        ),
    ]
